<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RollForward>Major</RollForward>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../XNA Monogame Pixel Collision/AnimatedTexture2D.cs" Link="AnimatedTexture2D.cs" />
    <Compile Include="../XNA Monogame Pixel Collision/FpsDisplay.cs" Link="FpsDisplay.cs" />
    <Compile Include="../XNA Monogame Pixel Collision/GameTester.cs" Link="GameTester.cs" />
    <Compile Include="../XNA Monogame Pixel Collision/MouseCursor.cs" Link="MouseCursor.cs" />
    <Compile Include="../XNA Monogame Pixel Collision/PixelCollider.cs" Link="PixelCollider.cs" />
    <Compile Include="../XNA Monogame Pixel Collision/PixelCollisionUtils.cs" Link="PixelCollisionUtils.cs" />
    <MonoGameContentReference Include="../XNA Monogame Pixel Collision/Content/Content.mgcb" Link="Content/Content.mgcb" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Icon.ico" />
    <None Remove="Icon.bmp" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Icon.ico" LogicalName="Icon.ico" />
    <EmbeddedResource Include="Icon.bmp" LogicalName="Icon.bmp" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.*" />
    <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.*" />
  </ItemGroup>
</Project>
